' ====================================================
' This file was generated using cvpletter.py
' 
' Copyright (c) 2025 Troy Schrapel (visrealm)
' 
' source: pletter\font.bas
' cmd:    python cvpletter.py pletter\font.bas
' output: font.pletter.bas
' 
' ====================================================
' WARNING! Do NOT edit this file. Edit source file
' ====================================================

  font0Pletter: ' source: 256 bytes. compressed: 169 bytes
    DATA BYTE $1e, $00, $39, $00, $18, $00, $00, $2d
    DATA BYTE $01, $6c, $00, $25, $0f, $06, $fe, $01
    DATA BYTE $40, $0b, $11, $7e, $c0, $7c, $06, $fc
    DATA BYTE $40, $18, $10, $c6, $cc, $18, $30, $66
    DATA BYTE $00, $c6, $00, $38, $6c, $38, $76, $dc
    DATA BYTE $cc, $06, $76, $00, $30, $30, $60, $8a
    DATA BYTE $27, $0c, $15, $00, $2a, $18, $0c, $0f
    DATA BYTE $03, $00, $a0, $0b, $10, $66, $3c, $ff
    DATA BYTE $3c, $75, $66, $50, $39, $7d, $50, $5c
    DATA BYTE $c3, $18, $00, $7e, $00, $58, $6c, $00
    DATA BYTE $06, $a0, $2c, $41, $c0, $80, $00, $7c
    DATA BYTE $02, $ce, $de, $f6, $e6, $c6, $7c, $12
    DATA BYTE $72, $38, $80, $7e, $0f, $00, $c6, $06
    DATA BYTE $7c, $c0, $c0, $fe, $00, $fc, $0a, $06
    DATA BYTE $06, $3c, $06, $78, $5f, $44, $cc, $00
    DATA BYTE $fe, $0c, $5f, $fe, $66, $c0, $11, $52
    DATA BYTE $27, $1c, $08, $c6, $07, $ae, $0f, $0d
    DATA BYTE $7a, $ae, $2f, $0c, $02, $e2, $07, $7e
    DATA BYTE $06, $3a, $ed, $5b, $e7, $03, $30, $77
    DATA BYTE $66, $9f, $76, $7e, $80, $3a, $0b, $06
    DATA BYTE $a7, $a3, $bb, $05, $ef, $ff, $ff, $ff
    DATA BYTE $ff

  font1Pletter: ' source: 256 bytes. compressed: 170 bytes
    DATA BYTE $04, $7c, $c6, $de, $00, $c0, $01, $7e
    DATA BYTE $00, $38, $6c, $c6, $c6, $fe, $17, $02
    DATA BYTE $00, $fc, $03, $24, $02, $00, $17, $c0
    DATA BYTE $00, $c6, $04, $7c, $00, $f8, $cc, $c6
    DATA BYTE $00, $cc, $12, $f8, $00, $fe, $0d, $f8
    DATA BYTE $02, $78, $fe, $07, $c0, $d1, $1f, $ce
    DATA BYTE $97, $1f, $1d, $47, $36, $37, $7e, $18
    DATA BYTE $4e, $00, $47, $06, $00, $e0, $17, $cc
    DATA BYTE $d8, $f0, $d8, $4e, $cc, $17, $c0, $00
    DATA BYTE $a0, $37, $0f, $ee, $fe, $fe, $d6, $a1
    DATA BYTE $27, $07, $e6, $f6, $de, $57, $37, $07
    DATA BYTE $3f, $5d, $00, $27, $6c, $b4, $4f, $00
    DATA BYTE $d6, $1d, $de, $7c, $06, $0f, $d8, $37
    DATA BYTE $5f, $7c, $e7, $47, $ff, $5d, $57, $00
    DATA BYTE $67, $cd, $6a, $00, $9d, $36, $38, $07
    DATA BYTE $18, $2f, $fe, $6c, $07, $6c, $e7, $ba
    DATA BYTE $00, $08, $15, $18, $30, $e0, $9f, $06
    DATA BYTE $0c, $91, $06, $60, $27, $3c, $30, $c8
    DATA BYTE $00, $3c, $7f, $60, $30, $09, $18, $0c
    DATA BYTE $06, $02, $0f, $0c, $d2, $00, $0f, $10
    DATA BYTE $2d, $b5, $2c, $9f, $00, $ff, $ff, $ff
    DATA BYTE $ff, $f8

  font2Pletter: ' source: 256 bytes. compressed: 170 bytes
    DATA BYTE $01, $18, $24, $24, $18, $00, $a0, $00
    DATA BYTE $7c, $06, $7e, $08, $c6, $7e, $00, $c0
    DATA BYTE $00, $fc, $c6, $38, $c6, $fc, $0f, $c6
    DATA BYTE $c0, $0a, $c6, $7c, $00, $06, $00, $16
    DATA BYTE $ce, $17, $0f, $20, $fe, $c0, $0f, $1c
    DATA BYTE $36, $30, $78, $59, $30, $02, $0f, $c6
    DATA BYTE $16, $06, $fc, $92, $2e, $00, $00, $44
    DATA BYTE $25, $38, $18, $00, $3c, $2f, $ca, $31
    DATA BYTE $06, $38, $17, $0b, $cc, $d8, $f8, $cc
    DATA BYTE $17, $ba, $15, $17, $00, $06, $cc, $fe
    DATA BYTE $fe, $d6, $d6, $6d, $07, $2f, $cb, $4f
    DATA BYTE $c6, $5f, $6c, $0f, $45, $f1, $4f, $06
    DATA BYTE $d9, $0f, $83, $ca, $5f, $c0, $91, $87
    DATA BYTE $98, $3b, $7e, $3f, $0e, $ce, $0f, $36
    DATA BYTE $ee, $87, $36, $68, $38, $07, $d6, $38
    DATA BYTE $fe, $6c, $07, $6c, $38, $77, $6c, $4f
    DATA BYTE $50, $1e, $30, $07, $fe, $0c, $38, $00
    DATA BYTE $60, $fe, $00, $3f, $60, $cf, $d8, $d8
    DATA BYTE $15, $cf, $60, $3f, $3c, $99, $c5, $03
    DATA BYTE $c0, $60, $b5, $06, $00, $60, $c0, $76
    DATA BYTE $dc, $cf, $ed, $ff, $3f, $00, $ff, $ff
    DATA BYTE $ff, $f0

