' ====================================================
' This file was generated using cvpletter.py
' 
' Copyright (c) 2025 Troy Schrapel (visrealm)
' 
' source: pletter\logo.bas
' cmd:    python cvpletter.py pletter\logo.bas
' output: logo.pletter.bas
' 
' ====================================================
' WARNING! Do NOT edit this file. Edit source file
' ====================================================

  logoTopPletter: ' source: 192 bytes. compressed: 154 bytes
    DATA BYTE $00, $0f, $3f, $7f, $7f, $f8, $f0, $03
    DATA BYTE $f1, $f3, $80, $c0, $e0, $f0, $0c, $06
    DATA BYTE $f3, $00, $00, $06, $7c, $fe, $ff, $c7
    DATA BYTE $3c, $33, $00, $3f, $00, $8b, $0f, $0e
    DATA BYTE $3f, $24, $86, $07, $07, $9f, $bf, $04
    DATA BYTE $0f, $01, $01, $83, $e3, $27, $3c, $40
    DATA BYTE $ff, $00, $e3, $c3, $c7, $cf, $1e, $1c
    DATA BYTE $1e, $9e, $de, $00, $00, $1c, $c3, $e3
    DATA BYTE $f7, $00, $fc, $c2, $00, $80, $80, $03
    DATA BYTE $79, $00, $00, $d0, $13, $2d, $f1, $f1
    DATA BYTE $e7, $40, $c7, $00, $e7, $e3, $f1, $f0
    DATA BYTE $87, $00, $9f, $9f, $c0, $f0, $ff, $fe
    DATA BYTE $7c, $bc, $00, $bc, $3e, $3f, $1f, $1f
    DATA BYTE $0f, $07, $79, $6c, $78, $00, $7c, $c4
    DATA BYTE $02, $3f, $11, $07, $08, $fb, $7b, $7b
    DATA BYTE $fb, $2f, $e3, $83, $0e, $df, $de, $dc
    DATA BYTE $c0, $00, $36, $9e, $1e, $00, $c7, $46
    DATA BYTE $f0, $08, $00, $e7, $87, $07, $00, $03
    DATA BYTE $03, $6d, $00, $65, $7f, $00, $ff, $ff
    DATA BYTE $ff, $e0

