' ====================================================
' This file was generated using cvpletter.py
' 
' Copyright (c) 2025 Troy Schrapel (visrealm)
' 
' source: pletter\sprites.bas
' cmd:    python cvpletter.py pletter\sprites.bas
' output: sprites.pletter.bas
' 
' ====================================================
' WARNING! Do NOT edit this file. Edit source file
' ====================================================

  spillPattPletter: ' source: 192 bytes. compressed: 112 bytes
    DATA BYTE $1c, $00, $00, $01, $62, $03, $00, $01
    DATA BYTE $0a, $f8, $00, $80, $c0, $0d, $e0, $e0
    DATA BYTE $c0, $c0, $48, $0e, $1b, $0f, $0f, $4f
    DATA BYTE $07, $00, $03, $b1, $0f, $1d, $f0, $8f
    DATA BYTE $1f, $80, $13, $1d, $07, $1d, $1f, $26
    DATA BYTE $00, $05, $04, $c7, $10, $f0, $f8, $27
    DATA BYTE $00, $f0, $22, $40, $12, $0d, $04, $07
    DATA BYTE $1d, $3f, $00, $cc, $1e, $22, $69, $0c
    DATA BYTE $3d, $19, $1c, $fc, $fc, $20, $b6, $62
    DATA BYTE $4d, $39, $1d, $7f, $33, $00, $23, $82
    DATA BYTE $7b, $f0, $fc, $fe, $fe, $20, $e5, $00
    DATA BYTE $f0, $20, $d8, $3b, $1f, $ff, $ee, $00
    DATA BYTE $20, $8e, $1f, $f0, $fe, $0b, $aa, $1c
    DATA BYTE $24, $25, $42, $ff, $ff, $ff, $ff, $c0

