' ====================================================
' This file was generated using cvpletter.py
' 
' Copyright (c) 2025 Troy Schrapel (visrealm)
' 
' source: pletter\test.bas
' cmd:    python cvpletter.py pletter\test.bas
' output: G:\projects\retropipe\src\test.pletter.bas
' 
' ====================================================
' WARNING! Do NOT edit this file. Edit source file
' ====================================================

testPletter: ' source size: 6 bytes
    DATA BYTE $08, $01, $02, $01, $03, $04, $ff, $ff
    DATA BYTE $ff, $ff, $c0

