' ====================================================
' This file was generated using cvpletter.py
' 
' Copyright (c) 2025 Troy Schrapel (visrealm)
' 
' source: pletter\tiles.bas
' cmd:    python cvpletter.py pletter\tiles.bas
' output: tiles.pletter.bas
' 
' ====================================================
' WARNING! Do NOT edit this file. Edit source file
' ====================================================

  gridPletter: ' source: 240 bytes. compressed: 90 bytes
    DATA BYTE $0d, $ff, $80, $8d, $00, $ff, $00, $8d
    DATA BYTE $00, $fe, $01, $9e, $00, $80, $3c, $00
    DATA BYTE $00, $00, $7b, $01, $7c, $17, $2e, $ff
    DATA BYTE $f0, $16, $ff, $49, $3d, $92, $24, $0d
    DATA BYTE $02, $93, $25, $9b, $02, $24, $e7, $18
    DATA BYTE $9f, $0f, $3c, $37, $ff, $2e, $78, $fe
    DATA BYTE $0f, $f2, $ee, $0e, $0a, $f1, $07, $f2
    DATA BYTE $e0, $36, $27, $93, $a5, $69, $c9, $0a
    DATA BYTE $e1, $07, $27, $f2, $e7, $47, $87, $5c
    DATA BYTE $ff, $f2, $8f, $07, $27, $36, $4f, $36
    DATA BYTE $1e, $a5, $fe, $27, $7f, $07, $ff, $ff
    DATA BYTE $ff, $e0

  pipesPletter: ' source: 80 bytes. compressed: 47 bytes
    DATA BYTE $0d, $ff, $00, $0d, $00, $ff, $3f, $8d
    DATA BYTE $07, $3f, $fc, $8f, $07, $fc, $81, $26
    DATA BYTE $00, $0a, $81, $e6, $00, $0e, $28, $07
    DATA BYTE $03, $01, $00, $0d, $ff, $e0, $c0, $80
    DATA BYTE $41, $00, $c0, $e0, $ff, $a0, $14, $03
    DATA BYTE $07, $ff, $ff, $ff, $ff, $ff, $c0

  bordersPletter: ' source: 56 bytes. compressed: 29 bytes
    DATA BYTE $1e, $c1, $3c, $00, $06, $00, $1a, $ff
    DATA BYTE $ff, $00, $1b, $00, $07, $03, $0f, $07
    DATA BYTE $c1, $81, $01, $46, $00, $00, $cf, $00
    DATA BYTE $ff, $ff, $ff, $ff, $fc

  gridColorPletter: ' source: 72 bytes. compressed: 25 bytes
    DATA BYTE $1f, $45, $36, $00, $15, $00, $36, $47
    DATA BYTE $75, $00, $fc, $16, $3d, $15, $75, $9f
    DATA BYTE $17, $74, $8f, $16, $75, $ff, $ff, $ff
    DATA BYTE $fc

  ffwdPattPletter: ' source: 96 bytes. compressed: 61 bytes
    DATA BYTE $06, $00, $1f, $20, $80, $00, $00, $ff
    DATA BYTE $00, $00, $88, $23, $cc, $ee, $05, $f8
    DATA BYTE $04, $4d, $00, $00, $14, $1f, $1f, $00
    DATA BYTE $ee, $cc, $88, $56, $00, $1b, $16, $82
    DATA BYTE $14, $f8, $f8, $00, $2f, $69, $3f, $00
    DATA BYTE $ac, $2f, $fc, $d3, $00, $49, $14, $2f
    DATA BYTE $0f, $e3, $2f, $ff, $49, $14, $2f, $f0
    DATA BYTE $ff, $ff, $ff, $ff, $80

  ffwdColorPletter: ' source: 96 bytes. compressed: 37 bytes
    DATA BYTE $0d, $f4, $74, $96, $00, $f4, $01, $cd
    DATA BYTE $00, $74, $e6, $00, $14, $d3, $15, $07
    DATA BYTE $f4, $c6, $0f, $44, $b3, $2f, $f7, $bf
    DATA BYTE $00, $9a, $2f, $14, $67, $15, $07, $df
    DATA BYTE $0f, $ff, $ff, $ff, $f8

