' ====================================================
' This file was generated using cvpletter.py
' 
' Copyright (c) 2025 Troy Schrapel (visrealm)
' 
' source: pletter\title.bas
' cmd:    python cvpletter.py pletter\title.bas
' output: title.pletter.bas
' 
' ====================================================
' WARNING! Do NOT edit this file. Edit source file
' ====================================================

  titleLogoPletter: ' source: 768 bytes. compressed: 298 bytes
    DATA BYTE $20, $00, $03, $07, $0f, $1f, $3f, $9b
    DATA BYTE $00, $7f, $e3, $00, $ff, $c3, $00, $f1
    DATA BYTE $e0, $03, $00, $e1, $e3, $e3, $e7, $6a
    DATA BYTE $00, $08, $00, $30, $e1, $e1, $12, $c0
    DATA BYTE $f8, $0d, $fc, $fe, $fe, $ff, $63, $00
    DATA BYTE $fe, $fc, $b5, $00, $9b, $12, $00, $30
    DATA BYTE $00, $80, $00, $83, $87, $5d, $8f, $6a
    DATA BYTE $6b, $d0, $00, $08, $0f, $8f, $87, $0f
    DATA BYTE $c3, $c0, $c0, $00, $9b, $00, $1f, $1c
    DATA BYTE $2f, $f8, $f0, $5e, $e0, $36, $f0, $f8
    DATA BYTE $0e, $6a, $1f, $5a, $1f, $68, $1e, $53
    DATA BYTE $7f, $3f, $34, $55, $e0, $6c, $37, $e0
    DATA BYTE $07, $83, $00, $87, $87, $c7, $c7, $08
    DATA BYTE $3d, $c7, $87, $0a, $03, $03, $39, $81
    DATA BYTE $81, $36, $fc, $f7, $00, $c6, $90, $9d
    DATA BYTE $0c, $4a, $c6, $4c, $1f, $07, $b0, $5f
    DATA BYTE $c0, $c1, $c3, $46, $c7, $00, $cf, $0f
    DATA BYTE $8f, $00, $8f, $b5, $00, $1a, $1f, $3f
    DATA BYTE $c1, $e2, $fa, $f8, $ac, $00, $00, $d6
    DATA BYTE $40, $23, $e1, $e7, $3d, $9f, $9f, $58
    DATA BYTE $df, $85, $83, $01, $1d, $fc, $df, $61
    DATA BYTE $e0, $3f, $b5, $1e, $de, $c3, $df, $fc
    DATA BYTE $c3, $94, $af, $8d, $16, $cb, $f8, $89
    DATA BYTE $9f, $01, $03, $78, $00, $e0, $68, $df
    DATA BYTE $74, $00, $08, $87, $d1, $11, $0f, $e5
    DATA BYTE $2b, $2c, $bb, $3e, $00, $fc, $68, $e1
    DATA BYTE $d5, $1f, $b4, $e7, $7c, $fb, $74, $8a
    DATA BYTE $5b, $81, $c1, $c7, $1b, $f1, $f1, $f9
    DATA BYTE $51, $00, $08, $0c, $c1, $01, $bc, $00
    DATA BYTE $ff, $ff, $29, $00, $d6, $81, $94, $d7
    DATA BYTE $00, $9f, $df, $1f, $00, $3f, $3e, $f6
    DATA BYTE $3a, $af, $6e, $66, $27, $bf, $f0, $fe
    DATA BYTE $c7, $f5, $c4, $f6, $2a, $f0, $7a, $00
    DATA BYTE $4d, $00, $60, $c3, $c1, $f5, $87, $f4
    DATA BYTE $ec, $03, $d1, $de, $35, $1f, $7f, $ad
    DATA BYTE $d7, $6f, $09, $ab, $0a, $e0, $51, $88
    DATA BYTE $d6, $8b, $fb, $53, $53, $16, $ff, $ff
    DATA BYTE $ff, $ff

  titlePipePattPletter: ' source: 312 bytes. compressed: 84 bytes
    DATA BYTE $1e, $03, $3c, $00, $80, $00, $78, $c0
    DATA BYTE $00, $01, $f1, $00, $00, $e3, $00, $80
    DATA BYTE $5e, $00, $7d, $ff, $1d, $69, $00, $2c
    DATA BYTE $f7, $0f, $d4, $37, $0f, $02, $ff, $56
    DATA BYTE $6f, $02, $00, $db, $19, $b7, $5f, $de
    DATA BYTE $12, $9f, $17, $d9, $7f, $42, $b5, $72
    DATA BYTE $00, $b7, $6a, $9f, $54, $7d, $8a, $2a
    DATA BYTE $9a, $0a, $7d, $07, $3f, $f7, $57, $df
    DATA BYTE $27, $69, $4f, $14, $a3, $09, $03, $55
    DATA BYTE $be, $00, $5c, $db, $30, $2f, $32, $02
    DATA BYTE $ff, $ff, $ff, $fc

  titlePipeColorPletter: ' source: 312 bytes. compressed: 126 bytes
    DATA BYTE $1e, $10, $3c, $00, $f4, $00, $f9, $0f
    DATA BYTE $fe, $38, $00, $f5, $00, $ff, $ff, $4d
    DATA BYTE $0e, $00, $f5, $67, $00, $f1, $a1, $00
    DATA BYTE $41, $41, $db, $33, $da, $0f, $7d, $00
    DATA BYTE $09, $88, $05, $44, $00, $40, $45, $cf
    DATA BYTE $01, $9e, $17, $15, $7c, $00, $31, $11
    DATA BYTE $04, $11, $1f, $17, $17, $1e, $00, $1f
    DATA BYTE $66, $1f, $04, $7d, $17, $87, $f3, $6f
    DATA BYTE $e5, $c9, $00, $24, $f7, $a7, $00, $d0
    DATA BYTE $07, $a1, $f0, $70, $70, $59, $7e, $00
    DATA BYTE $0a, $96, $aa, $a5, $23, $07, $4e, $00
    DATA BYTE $4f, $4f, $ef, $07, $9e, $17, $14, $7c
    DATA BYTE $00, $cf, $ee, $b4, $00, $4f, $e6, $13
    DATA BYTE $11, $0f, $92, $51, $51, $ff, $4f, $7f
    DATA BYTE $be, $00, $37, $d3, $27, $e6, $00, $1f
    DATA BYTE $b7, $07, $ff, $ff, $ff, $fe

  titlePipeNamesPletter: ' source: 320 bytes. compressed: 86 bytes
    DATA BYTE $21, $60, $75, $76, $62, $20, $be, $70
    DATA BYTE $00, $1b, $60, $78, $79, $37, $70, $77
    DATA BYTE $c1, $00, $80, $7a, $7b, $06, $1f, $7d
    DATA BYTE $7e, $71, $64, $f8, $00, $81, $20, $7e
    DATA BYTE $63, $1f, $65, $74, $6e, $74, $df, $06
    DATA BYTE $00, $82, $74, $73, $ab, $06, $1f, $61
    DATA BYTE $6c, $7c, $6c, $f8, $00, $83, $35, $6c
    DATA BYTE $72, $78, $1f, $7f, $68, $df, $1c, $00
    DATA BYTE $84, $1f, $66, $3d, $6a, $6b, $42, $00
    DATA BYTE $6d, $6f, $1f, $3d, $67, $69, $67, $9f
    DATA BYTE $3f, $1b, $ff, $ff, $ff, $f0

