name: Build macOS

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-common.yml
    with:
      artifact-name-suffix: macos
      run-windows: false
      run-linux: false
      run-macos: true
