name: Build Linux

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-common.yml
    with:
      artifact-name-suffix: linux
      run-windows: false
      run-linux: true
      run-macos: false
